site_name: Computational Physics



extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math



theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
 
  
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni


nav:
- Home: index.md
- Why Computational Physics: WhyComputationalPhysics.md


- Getting started:
  - Guide to starting Python: GettingStarted/anaconda.md
  - Guide to Python Libraries: GettingStarted/lib.md
  - Setting up Python Environment: GettingStarted/env.md
  - Installing Jupyter Notebook : GettingStarted/jupyter.md
  - How to Git: GettingStarted/git.md
  
- Python:
  - Data Structure : Python/ds.md
  - Loops and Conditions: Python/lnc.md
  - Function and Class: Python/fnc.md
  
  
- Numerical Methods:
  - Introduction : NumericalMethods/intro/Numerical-Methods.md
  - Special Functions : NumericalMethods/special-function/Special-Functions.md
  - Diffusion: NumericalMethods/Diffusion/Diffusion.md
  - Ncharges: NumericalMethods/Ncharges/Ncharges.md
  - Laplace : NumericalMethods/Laplace/laplace.md
  
- Monte Carlo Simulation:
  - Getting Started Monte Carlo Simulation : Montecarlo/GettingStarted/intro.md
  - Algorithms in Monte Carlo Simulation : Montecarlo/GettingStarted/intro.md
  - Random Walk: Montecarlo/RandomWalk/Rwalk.md
  - Lottary Model: Montecarlo/Lotto/lotto.md
  - Ideal Gas: Montecarlo/IdealGas/IdealGas.md
  - Harmonic Oscillator: Montecarlo/Oscillator/Oscillator.md
  - Ising Model: Montecarlo/IzingModel/Izing2D.md
  - Percolation : Montecarlo/Percolation/percol.md
  - Hard Disk : Montecarlo/HardDisk/hd.md
  - Quantum Monte Carlo: Montecarlo/Levy/levy.md
  - Bose-Einstein Condensation: Montecarlo/BEC/bec.md
  
- Optimization:
  - Optimization: optimization/intro/Optimization.md
  - Simulated Annealing: optimization/SimulatedAnealing/simulatedAnn.md

  
- Path Integral:
  - Getting Started with Path Integral: PathIntegral/Intro/Intro.md
  
- Fractals and Chaos:
  - Fern: FractalChaos/Fern/fern.md 
            
- References: References.md
  
   
      


