site_name: Tutorials in Statistical Physics


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    


theme:
  name: 'material'
  highlightjs: true
  hljs_languages: [python]
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 

  
  
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni
      


nav:
- Home: index.md
- Why Computational Physics: WhyComputationalPhysics.md
- Introduction : Montecarlo/GettingStarted/intro.md
- Algorithms : Montecarlo/GettingStarted/intro.md
- Ideal Gas: Montecarlo/IdealGas/IdealGas.md
- Harmonic Oscillator: Montecarlo/Oscillator/Oscillator.md
- Ising Model: Montecarlo/IzingModel/Izing2D.md
- Percolation : Montecarlo/Percolation/percol.md
- Hard Disk : Montecarlo/HardDisk/hd.md
- Quantum Monte Carlo: Montecarlo/Levy/levy.md
- Bose-Einstein Condensation: Montecarlo/BEC/bec.md
- Simulated Annealing: optimization/SimulatedAnealing/simulatedAnn.md
- Path Integral: PathIntegral/Intro/Intro.md
- References: References.md
  
   
      


